### ISSUE TITLE
Can't make it run after upgrade from 3 to 4 - AttributeError: 'NoneType' object has no attribute 'dashboard_dir'

### ISSUE THREAD

**Issue by DPH** [hassio-addons/app-appdaemon#36]
# Problem/Motivation

> Have read web and searched but can't find how to fix 

## Expected behavior

> (What you expected to happen)

## Actual behavior

see error below: AttributeError: 'NoneType' object has no attribute 'dashboard_dir'

> 
```Add-on version: 0.2.6
 You are running the latest version of this add-on.
 System: HassOS 4.11  (armv7 / raspberrypi3)
 Home Assistant Core: 0.112.3
 Home Assistant Supervisor: 228
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:25:52] INFO: Starting AppDaemon...
2020-07-15 18:25:55.576384 INFO AppDaemon: AppDaemon Version 4.0.3 starting
2020-07-15 18:25:55.577468 INFO AppDaemon: Python version is 3.8.2
2020-07-15 18:25:55.578946 INFO AppDaemon: Configuration read from: /config/appdaemon/appdaemon.yaml
2020-07-15 18:25:55.580189 INFO AppDaemon: Added log: AppDaemon
2020-07-15 18:25:55.581358 INFO AppDaemon: Added log: Error
2020-07-15 18:25:55.582283 INFO AppDaemon: Added log: Access
2020-07-15 18:25:55.583516 INFO AppDaemon: Added log: Diag
2020-07-15 18:25:55.652426 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-07-15 18:25:55.729895 INFO HASS: HASS Plugin Initializing
2020-07-15 18:25:55.730995 INFO HASS: HASS Plugin initialization complete
2020-07-15 18:25:55.733438 INFO AppDaemon: HTTP is disabled
2020-07-15 18:25:55.780215 INFO HASS: Connected to Home Assistant 0.112.3
2020-07-15 18:25:55.872558 INFO AppDaemon: App 'sky_switch' added
2020-07-15 18:25:55.874380 INFO AppDaemon: App 'sky_away' added
2020-07-15 18:25:55.877605 INFO AppDaemon: Found 2 total apps
2020-07-15 18:25:55.879642 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
2020-07-15 18:25:56.011052 INFO HASS: Evaluating startup conditions
2020-07-15 18:25:56.126371 INFO AppDaemon: Got initial state from namespace default
2020-07-15 18:25:57.891943 INFO AppDaemon: Scheduler running in realtime
2020-07-15 18:25:57.903576 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-07-15 18:25:57.916181 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/sky_switch.py
2020-07-15 18:25:57.933421 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/sky_away.py
2020-07-15 18:25:57.939119 INFO AppDaemon: Initializing app sky_switch using class SkySwitch from module sky_switch
2020-07-15 18:25:57.942914 WARNING sky_switch: ------------------------------------------------------------
2020-07-15 18:25:57.944444 WARNING sky_switch: Unexpected error initializing app: sky_switch:
2020-07-15 18:25:57.945779 WARNING sky_switch: ------------------------------------------------------------
2020-07-15 18:25:57.951565 WARNING sky_switch: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
2020-07-15 18:25:57.953163 WARNING sky_switch: ------------------------------------------------------------
2020-07-15 18:25:57.954672 INFO AppDaemon: Initializing app sky_away using class SkyAway from module sky_away
2020-07-15 18:25:57.959345 WARNING sky_away: ------------------------------------------------------------
2020-07-15 18:25:57.960849 WARNING sky_away: Unexpected error initializing app: sky_away:
2020-07-15 18:25:57.962173 WARNING sky_away: ------------------------------------------------------------
2020-07-15 18:25:57.964288 WARNING sky_away: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 820, in check_app_updates
    await self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 279, in init_object
    "object": app_class(
  File "/usr/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 46, in __init__
    adbase.ADBase.__init__(self, ad, name, logging, args, config, app_config, global_vars)
  File "/usr/lib/python3.8/site-packages/appdaemon/adbase.py", line 75, in __init__
    self.dashboard_dir = self.AD.http.dashboard_dir
AttributeError: 'NoneType' object has no attribute 'dashboard_dir'
2020-07-15 18:25:57.965700 WARNING sky_away: ------------------------------------------------------------
2020-07-15 18:25:57.968618 WARNING AppDaemon: Unable to find module sky_switch - initialize() skipped
2020-07-15 18:25:57.971115 WARNING AppDaemon: Unable to find module sky_away - initialize() skipped
2020-07-15 18:25:57.974318 INFO AppDaemon: App initialization complete
```

## Steps to reproduce

> Not sure

## Proposed changes

Looking for advice on what I have done wrong - and how to put it right.

Thanks David

**Comment by DPH** [comment]
Solved! For anyone else having this issue upgrading from 3 to 4 this is how I fixed it:
 - uninstall appdaemon completely
 - rename the appdaemon directory 
 - reinstall appdaemon - which creates a working config.

Regards David
