### ISSUE TITLE
Entity_state Object in Self is "undefined" in OnStateAvailable callback.

### ISSUE THREAD

**Issue by n8hjp** [hassio-addons/app-appdaemon#47]
# Problem/Motivation

My custom Widgets no longer work in 4.0.5.       

## Expected behavior

In the past the entity_state object had sub-objects names as the entity name.     Now in the OnStateAvailable call it is named "undefined."      In the OnStateUpdate, it has the proper name, but also has an additional object with the name "undefined."   (This isn't a problem, but is different behavior than before.

## Actual behavior

Here is the specific example of the self object during these calls:

OnStateAvailable:

entity_state: Object   input_text.condition_alarm: Object
    **undefined: Object**
        attributes: {editable: true, friendly_name: "Alarm Condition", max: 100, min: 0, mode: "text", …}
       context: {id: "8dc732a1ea1d11ea95ca0bb8702f7428", parent_id: "8dc13de0ea1d11eab508bdfd74e861f9", user_id: null}
       entity_id: "input_text.condition_alarm"
       last_changed: "2020-08-29T17:32:04.221198+00:00"
       last_updated: "2020-08-29T17:32:04.221198+00:00"
       state: "Green"

OnStateUpdate:

entity_state: Object
   input_text.condition_alarm: Object
        attributes: {editable: true, min: 0, max: 100, pattern: null, mode: "text", …}
        context: {id: "0bcfc9cfea1f11eaaa5b91aa09726c57", parent_id: "0bc73117ea1f11ea920fe9ce64514d2c", user_id: null}
        entity_id: "input_text.condition_alarm"
        last_changed: "2020-08-29T17:42:45.192048+00:00"
        last_updated: "2020-08-29T17:42:45.192048+00:00"
        state: "Green".   
   **undefined: Object**
        attributes: {editable: true, friendly_name: "Alarm Condition", max: 100, min: 0, mode: "text", …}
       context: {id: "8dc732a1ea1d11ea95ca0bb8702f7428", parent_id: "8dc13de0ea1d11eab508bdfd74e861f9", user_id: null}
       entity_id: "input_text.condition_alarm"
       last_changed: "2020-08-29T17:32:04.221198+00:00"
       last_updated: "2020-08-29T17:32:04.221198+00:00"
       state: "Green"

## Steps to reproduce

I have some poorly written rather complex widgets (As most good programming, I really mean to clean up the code, but it has been working...).       The most complex one watch 5 different entity and present a widget with probably all too much information in it  :-)

## Proposed changes

I removed and reinstalled 4.0.5 to see if something has gotten messed.    Running Hassio HassOS 4.12 and Supervisor version 235.

**Comment by frenck** [comment]
Add-ons wrap existing software, in this case, AppDaemon.

As this issue is happening inside AppDaemon (and not part of the add-on wrapping), please report your issue with AppDaemon itself.

Thanks 👍
