### ISSUE TITLE
Dashboard actions not working in AppDaemon v4.5.3 (works in 4.5.2 and 4.5.5)

### ISSUE THREAD

**Issue by yawamdam** [hassio-addons/app-appdaemon#402]
### Podsumowanie

Po automatycznej aktualizacji dodatku AppDaemon do wersji v4.5.3 w Home Assistant OS, przestały działać wszystkie dashboardy (HADashboard) na ekranach dotykowych Raspberry Pi 7". Interfejs wyświetlał aktualne dane (np. obraz z kamery, stany czujników), ale żadne akcje użytkownika (np. naciśnięcia przycisków) nie były rejestrowane.

Nie wprowadzałem żadnych zmian w plikach konfiguracyjnych. Aktualizacja została przeprowadzona automatycznie przez Supervisor.

W logach pojawiały się powtarzające się błędy:

Missing return statement on request handler
Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 698, in finish_response
prepare_meth = resp.prepare
^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'prepare'

### Reprodukcja

- Home Assistant OS z dodatkiem AppDaemon zarządzanym przez Supervisor
- Dashboardy wyświetlane na kilku Raspberry Pi z ekranami dotykowymi
- Brak zmian w konfiguracji

### Przetestowane wersje

✅ Działa poprawnie:
- v4.5.2
- v4.5.5

❌ Nie działa:
- v4.5.3

### Dodatkowe informacje

Zweryfikowałem to również niezależnie w środowisku Docker: ta sama konfiguracja, bez żadnych zmian — problem występuje tylko w wersji 4.5.3. Wygląda na to, że to regresja.

Dziękuję za utrzymanie tego dodatku!

**Comment by frenck** [comment]
Sorry I don't speak this language.

../Frenck
